### PR TITLE
Added Waifu command and another image grab method

### PR DESCRIPTION
**Pull request by BurritoWrapped**
Added img grab method, compared to the gif function, also a waifu + neko command.

### CODE REVIEW

**Comment by lionirdeadman** [comment]
You have multiple instances of

```
        images = await self.config.smug()
```

which are not supposed to be there.

Also, as I said in private, you should offer a certain amount of results inside the default config so if nekos.life goes down, it doesn't affect the usability of the bot.

**Comment by BurritoWrapped** [comment]
@lionirdeadman Anything else I should work on?

**Comment by BurritoWrapped** [comment]
Added an 8ball cog, which uses nekos.life for the images

**Comment by lionirdeadman** [comment]
You didn't add a list of results for each new command and you still mention smug in some places, I think it actually doesn't work with the way you wrote it either. I see you've given up on 8ball too which is good because it's out of scope for this PR.

**Pull request closed without merging**
