### PR TITLE
Confessions

### PR DESCRIPTION
**Pull request by 6days9weeks**
I somehow got the embed to working but can’t think of a way to do `#5th Confession` like thing for the number of confessions

### CODE REVIEW

**Comment by 6days9weeks** [comment]
Also change the color of the embed if needed I set it to match my bots

**Comment by lionirdeadman** [comment]
You'd need to store a count per-guild and increase that by one every time the command is used so it can be used in the embed.

**Comment by 6days9weeks** [comment]
> You'd need to store a count per-guild and increase that by one every time the command is used so it can be used in the embed.

I will try I guess still new to dpy

**Comment by lionirdeadman** [comment]
We can try that in another PR if you want. Feel free to DM if you want pointers. Although as mentioned in #29, I've never used Red's settings which we'd wanna use for that so it'll be a learning experience for me too.

**Comment by 6days9weeks** [comment]
> We can try that in another PR if you want. Feel free to DM if you want pointers. Although as mentioned in #29, I've never used Red's settings which we'd wanna use for that so it'll be a learning experience for me too.

Alrighty you're so nice omg

**Comment by xPolar** [comment]
Hey @6days9weeks, could I attempt this as well?

**Comment by 6days9weeks** [comment]
> Hey @6days9weeks, could I attempt this as well?

Sure I'll be glad to see how you do it. I fixed it in a private repo but it's not working very well cause I don't really know how the cogs work on red.

**Comment by xPolar** [comment]
Alright, could I ask you for how you store the confessions and the confession channel for each guild?

**Comment by 6days9weeks** [comment]
> Alright, could I ask you for how you store the confessions and the confession channel for each guild?

I store it in a single json file. I haven't rebooted my bot since that I'm pretty sure it will reset if I reboot it that's why I said it's not working very well.

**Comment by xPolar** [comment]
Alright, I have another question. Should the bot randomly select a guild to submit the confession to, allow the user to pick from a list of mutual servers that also have confessions, or allow them to choose from a list of random servers with confession channels?

**Comment by lionirdeadman** [comment]
Currently, we store a list of channels and check which ones the user has in common with the bot if I recall correctly.

You can see this here : https://github.com/Jintaku/Jintaku-Cogs-V3/blob/c6351f6c4adc882776e1386e03405e8f31d40764/confession/confession.py#L63

Considering how you should store the information needed for this, you can either continue using what we were doing with Config. You can see how to use Config here : https://docs.discord.red/en/stable/framework_config.html

**Comment by xPolar** [comment]
Red looks so extremely horrible, I'll still make an attempt at this however Red's way of storing data is complex for no reason what so ever. They should just make users use something like MongoDB.

**Pull request closed without merging**
