### PR TITLE
Remove another gif

### PR DESCRIPTION
**Pull request by Sandvich**
The gif in question made some members of our server uncomfortable, so I've opened this PR to remove it.
Thanks.

### CODE REVIEW

**Comment by lionirdeadman** [comment]
I'd like to know exactly what makes people uncomfortable in this gif to avoid adding some which would make people uncomfortable. :thinking:

**Comment by ChangelingRain** [comment]
Personally, it's that this gif only has one person in it, so it's just kind of lonely and doesn't feel appropriate as a cuddle gif

**Comment by lionirdeadman** [comment]
In that case, these should also be removed.

https://cdn.weeb.sh/images/B1S1I87vZ.gif
https://cdn.weeb.sh/images/HkzArUmvZ.gif

**Comment by NiramayS** [comment]
> 
> 
> I'd like to know exactly what makes people uncomfortable in this gif to avoid adding some which would make people uncomfortable. 🤔

To preface this, I am the owner of the server which Sandvich is talking about. (Sandvich can confirm if necessary)

The attire of the person in the gif is a little NSFW/revealing and has made a younger member on our server uncomfortable. Plus, as other people have noticed, it's only one person in what should be a cuddle gif, and as such it's kinda inappropriate.

**Comment by Sandvich** [comment]
As for the other two gifs you mentioned, they could certainly be removed in theory, but the main issue was the revealing clothing on an underage character

**Comment by lionirdeadman** [comment]
Ah, I see.

Nice to meet y'all btw and thanks for sending these PRs.

**Pull request merged**
